// One place to load and query the entity data.
// The JSON is generated by scripts/build-data.mjs from data/*.csv.

import data from '../data/entities.json'
import { HUB_TYPES, NON_PAGE_TYPES } from './site.mjs'

export const allEntities = data

// Rows that become their own page. release_fact rows are evidence, not pages.
export const pageEntities = data.filter((entity) => !NON_PAGE_TYPES.includes(entity.entityType))

export const releaseFacts = data.filter((entity) => entity.entityType === 'release_fact')

export const hubFor = (entityType) => HUB_TYPES.find((hub) => hub.type === entityType)

export const entitiesOfType = (entityType) =>
  pageEntities.filter((entity) => entity.entityType === entityType)

export const bySlug = new Map(pageEntities.map((entity) => [entity.slug, entity]))

export const urlFor = (entity) => {
  const hub = hubFor(entity.entityType)
  return hub ? `/${hub.slug}/${entity.slug}` : `/${entity.slug}`
}

/**
 * Sibling pages for the "related" block. Prefers names listed in the row's own
 * related_entities column, then falls back to others of the same type so no
 * page is ever an orphan.
 */
export function relatedFor(entity, limit = 4) {
  const normalise = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

  const named = entity.relatedEntities
    .map((name) => bySlug.get(normalise(name)))
    .filter((match) => match && match.slug !== entity.slug)

  const sameType = entitiesOfType(entity.entityType).filter(
    (other) => other.slug !== entity.slug && !named.some((match) => match.slug === other.slug),
  )

  return [...named, ...sameType].slice(0, limit)
}

// Plain-English labels for the confidence badge shown on every entity page.
export const STATUS_LABEL = {
  OFFICIAL_CONFIRMED: 'Confirmed by Rockstar',
  PRESS_REPORTED: 'Reported by the press',
  COMMUNITY_IDENTIFIED: 'Spotted by the community',
  UNCONFIRMED: 'Not confirmed',
}

export const TIER_LABEL = {
  TIER_1_OFFICIAL: 'Official source',
  TIER_2_MAJOR_PRESS: 'Major press',
  TIER_3_COMMUNITY: 'Community source',
  TIER_4_UNSOURCED: 'No source',
}
