// One place to load and query the entity data.
// The JSON is generated by scripts/build-data.mjs from data/*.csv.

import data from '../data/entities.json'
import { HUB_TYPES, NON_PAGE_TYPES } from './site.mjs'

export const allEntities = data

// Rows that become their own page. release_fact rows are evidence, not pages.
export const pageEntities = data.filter((entity) => !NON_PAGE_TYPES.includes(entity.entityType))

export const releaseFacts = data.filter((entity) => entity.entityType === 'release_fact')

export const hubFor = (entityType) => HUB_TYPES.find((hub) => hub.type === entityType)

export const entitiesOfType = (entityType) =>
  pageEntities.filter((entity) => entity.entityType === entityType)

export const bySlug = new Map(pageEntities.map((entity) => [entity.slug, entity]))

export const urlFor = (entity) => {
  const hub = hubFor(entity.entityType)
  return hub ? `/${hub.slug}/${entity.slug}` : `/${entity.slug}`
}

/**
 * Sibling pages for the "related" block. Prefers names listed in the row's own
 * related_entities column, then falls back to others of the same type so no
 * page is ever an orphan.
 */
export function relatedFor(entity, limit = 4) {
  const normalise = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

  const named = entity.relatedEntities
    .map((name) => bySlug.get(normalise(name)))
    .filter((match) => match && match.slug !== entity.slug)

  const sameType = entitiesOfType(entity.entityType).filter(
    (other) => other.slug !== entity.slug && !named.some((match) => match.slug === other.slug),
  )

  return [...named, ...sameType].slice(0, limit)
}

// Plain-English labels for the confidence badge shown on every entity page.
export const STATUS_LABEL = {
  OFFICIAL_CONFIRMED: 'Confirmed by Rockstar',
  PRESS_REPORTED: 'Reported by the press',
  COMMUNITY_IDENTIFIED: 'Spotted by the community',
  UNCONFIRMED: 'Not confirmed',
}

export const TIER_LABEL = {
  TIER_1_OFFICIAL: 'Official source',
  TIER_2_MAJOR_PRESS: 'Major press',
  TIER_3_COMMUNITY: 'Community source',
  TIER_4_UNSOURCED: 'No source',
}

/* ---------- The search snippet ----------

   The title and the description are the only two lines a person reads before
   deciding whether to click. Search Console for 24 August to 20 September 2026
   says they were not clicking: 492 impressions at an average position of 8.51,
   and not one click on any query. A page-one result that nobody opens is a
   snippet problem, not a ranking problem.

   Every query that reached these pages carried the game name in it. "gta 6
   ambrosia". "blood records gta 6". "gta 6 devil woman". Two things kept the
   snippet from answering that. The title named the entry and the site and never
   the game. And the descriptions call it "Grand Theft Auto VI", which is the
   correct name to print on the page and the wrong one to put in a snippet,
   because it is not what anybody types into the box.

   None of this rewrites what a person wrote. The sentence under each result is
   still that entry's own sentence. This moves the words a searcher typed to the
   front of it and cuts the tail on a whole word. */

const GAME_NAMES = [
  [/Grand Theft Auto\s+(?:VI|6)\b/gi, 'GTA 6'],
  [/\bGTA\s*VI\b/g, 'GTA 6'],
  [/\bGTA6\b/gi, 'GTA 6'],
]

const saysGame = (text) => /\bGTA 6\b/.test(text)

export function metaTitle(entity) {
  return /gta\s*6|grand theft auto/i.test(entity.name) ? entity.name : `${entity.name} in GTA 6`
}

export function metaDescription(entity, max = 155) {
  let text = entity.shortDescription.trim()
  for (const [pattern, name] of GAME_NAMES) text = text.replace(pattern, name)

  const leadsWithName = text.toLowerCase().startsWith(entity.name.toLowerCase())

  // "Dinka is a fictional Japanese vehicle brand" becomes "Dinka in GTA 6 is a
  // fictional Japanese vehicle brand". The sentence still reads as English,
  // which a prefix bolted onto the front of it would not.
  const lead = leadsWithName
    ? `${entity.name} in GTA 6${text.slice(entity.name.length)}`
    : `${entity.name} in GTA 6. ${text}`

  if (!saysGame(text)) return clip(lead, max)

  // The sentence already names the game, so it needs no help from us. Unless it
  // names the game so late that the trim cuts it off, and then the lead form
  // earns its repetition: a snippet that never says GTA 6 answers nobody.
  const kept = clip(leadsWithName ? text : `${entity.name}. ${text}`, max)
  return saysGame(kept) ? kept : clip(lead, max)
}

/* ---------- In the game ----------

   Filled by hand after launch, in data/ingame.json (see docs/INGAME-DATA.md).
   build-data.mjs checks each entry and puts it on entity.inGame. An entry with
   no inGame gets nothing from these helpers, so its page is unchanged. */

const endStop = (text) => (/[.!?]$/.test(text) ? text : `${text}.`)

export function inGameHeading(entity) {
  const facts = entity.inGame
  if (!facts) return null
  if (entity.entityType === 'song') return `Which radio station plays ${entity.name}`
  if (facts.howToGetThere) return `How to get to ${entity.name} in GTA 6`
  if (!facts.location && typeof facts.buyable === 'boolean') return `Can you buy ${entity.name} in GTA 6`
  return `Where to find ${entity.name} in GTA 6`
}

// Rows for the fact list, in reading order. Only filled fields appear.
export function inGameRows(entity) {
  const facts = entity.inGame
  if (!facts) return []
  return [
    ['Radio station', facts.radioStation],
    ['Location', facts.location],
    ['How to get it', facts.howToGet],
    ['How to get there', facts.howToGetThere],
    ['Can you buy it', typeof facts.buyable === 'boolean' ? (facts.buyable ? 'Yes' : 'No') : undefined],
    ['Price', facts.price],
    ['Class', facts.class],
  ].filter(([, value]) => value)
}

// The one fact worth a place in the search snippet, as a finished sentence.
function inGameSnippet(entity) {
  const facts = entity.inGame
  if (!facts) return null
  if (facts.radioStation) return `Radio station: ${endStop(facts.radioStation)}`
  if (facts.location) return `Where to find it: ${endStop(facts.location)}`
  if (facts.howToGetThere) return `How to get there: ${endStop(facts.howToGetThere)}`
  if (typeof facts.buyable === 'boolean') return `Can you buy it: ${facts.buyable ? 'Yes' : 'No'}.`
  return null
}

// The normal description, plus the in-game fact only when the whole line still
// fits in 160 characters and the description was not already cut short.
export function metaDescriptionWithInGame(entity, max = 160) {
  const base = metaDescription(entity)
  const extra = inGameSnippet(entity)
  if (!extra || base.endsWith('...')) return base
  const joined = `${endStop(base)} ${extra}`
  return joined.length <= max ? joined : base
}

// Adds the in-game facts to the page's main JSON-LD node as schema.org
// additionalProperty values. Only for node types that take that property
// (Product, Place and its kinds). Songs are MusicRecording, which does not, so
// their JSON-LD is left alone. Returns a new object; the input is not changed.
const TAKES_ADDITIONAL_PROPERTY = ['Product', 'Place', 'LocalBusiness', 'LandmarksOrHistoricalBuildings']

export function withInGameSchema(schema, entity) {
  const rows = inGameRows(entity)
  if (!rows.length) return schema
  const [node, ...rest] = schema['@graph']
  if (!TAKES_ADDITIONAL_PROPERTY.includes(node['@type'])) return schema
  const additionalProperty = rows.map(([name, value]) => ({ '@type': 'PropertyValue', name, value }))
  return { ...schema, '@graph': [{ ...node, additionalProperty }, ...rest] }
}

// Google cuts the snippet itself, mid-word and without warning. Cutting it here
// instead means the last thing a reader sees is a finished thought: a whole
// sentence where one ends in range, and a whole word where none does.
function clip(text, max) {
  if (text.length <= max) return text

  const head = text.slice(0, max)
  const sentence = Math.max(head.lastIndexOf('. '), head.lastIndexOf('? '), head.lastIndexOf('! '))
  if (sentence >= max * 0.6) return head.slice(0, sentence + 1)

  // The three dots are part of the snippet, so the whole word has to fit
  // inside the budget with them, not alongside it.
  const stem = text.slice(0, max - 3)
  const word = stem.lastIndexOf(' ')
  return `${stem.slice(0, word > 0 ? word : max - 3).replace(/[\s,;:-]+$/, '')}...`
}
